packages/pancake-uikit/src/index.ts

When I made the `TabMenu` component... I didn't export it, so it can't yet be used 🤦 
This PR adds it to the index exports.

chore(tab-menu): Add tab menu to src/index exports

---

packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/widgets/Menu/components/Panel.tsx

Updated drawer panel z-index to be 11 when its only on mobile.
On desktop, z-index value is initial
This is needed for Tooltip as Tooltip is beneath the drawer panel now.

fix: Set panel z index to 0 on desktop

---

packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
packages/pancake-uikit/src/widgets/Modal/Modal.tsx
packages/pancake-uikit/src/widgets/Modal/index.tsx
packages/pancake-uikit/src/widgets/Modal/styles.tsx
packages/pancake-uikit/src/widgets/Modal/types.ts

Split modal components up and export them

[UI Kit] refactor(uikit):  Modal

---

packages/pancake-uikit/jest.config.js
packages/pancake-uikit/src/__tests__/components/alert.test.tsx
packages/pancake-uikit/src/__tests__/components/balanceinput.test.tsx
packages/pancake-uikit/src/__tests__/components/breadcrumbs.test.tsx
packages/pancake-uikit/src/__tests__/components/button.test.tsx
packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
packages/pancake-uikit/src/__tests__/components/card.test.tsx
packages/pancake-uikit/src/__tests__/components/checkbox.test.tsx
packages/pancake-uikit/src/__tests__/components/dropdown.test.tsx
packages/pancake-uikit/src/__tests__/components/fallingbunnies.test.tsx
packages/pancake-uikit/src/__tests__/components/flex.test.tsx
packages/pancake-uikit/src/__tests__/components/heading.test.tsx
packages/pancake-uikit/src/__tests__/components/input.test.tsx
packages/pancake-uikit/src/__tests__/components/layouts.test.tsx
packages/pancake-uikit/src/__tests__/components/link.test.tsx
packages/pancake-uikit/src/__tests__/components/notificationdot.test.tsx
packages/pancake-uikit/src/__tests__/components/overlay.test.tsx
packages/pancake-uikit/src/__tests__/components/progress.test.tsx
packages/pancake-uikit/src/__tests__/components/radio.test.tsx
packages/pancake-uikit/src/__tests__/components/skeleton.test.tsx
packages/pancake-uikit/src/__tests__/components/spinner.test.tsx
packages/pancake-uikit/src/__tests__/components/svg.test.tsx
packages/pancake-uikit/src/__tests__/components/tabmenu.test.tsx
packages/pancake-uikit/src/__tests__/components/tag.test.tsx
packages/pancake-uikit/src/__tests__/components/text.test.tsx
packages/pancake-uikit/src/__tests__/components/toggle.test.tsx
packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx

Fix for: #20 - Added setupTest.js file and updated snaps

fix: Included setupTests.js and updated snap tests

---

packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
packages/pancake-uikit/src/widgets/Modal/Modal.tsx

We support devices down to 320px (i.e. iphone 8, or Hops' weird ass iPhone 12 pro).
The default min width for modals should reflect this. (Should it be even lower than 320 to allow for padding?)

fix(modal): Change modal min width to 320px

---

packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
packages/pancake-uikit/src/__tests__/components/tabmenu.test.tsx
packages/pancake-uikit/src/components/TabMenu/TabMenu.tsx

- Tab Menu had `scroll-overflow-y`, rather than `scroll-overflow-x` set... although it did still seem to scroll correctly even with the wrong axes set.
- Shrink side padding below 370px.

fix(tab-menu): Fix scroll overflow and tighten padding on sm phones

---

packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
packages/pancake-uikit/src/__tests__/components/pancaketoggle.test.tsx
packages/pancake-uikit/src/components/PancakeToggle/PancakeToggle.tsx
packages/pancake-uikit/src/components/PancakeToggle/StyledPancakeToggle.tsx
packages/pancake-uikit/src/components/PancakeToggle/index.stories.tsx
packages/pancake-uikit/src/components/PancakeToggle/index.tsx
packages/pancake-uikit/src/components/PancakeToggle/theme.ts
packages/pancake-uikit/src/components/PancakeToggle/types.ts
packages/pancake-uikit/src/index.ts
packages/pancake-uikit/src/theme/dark.ts
packages/pancake-uikit/src/theme/index.ts
packages/pancake-uikit/src/theme/light.ts

This PR adds PancakeToggle component - very similar to Toggle but with bunch of CSS to show handle as pancakes with butter. [PR 334](https://github.com/pancakeswap/pancake-swap-interface/pull/334) in exchange depends on this.
Possible improvements:
- Right now neither `Toggle` nor `PancakeToggle` support responsive array syntax similar (as `styled-system` components), so responsiveness has to be achieved with media queries hook. Seems to be that UIKit components in general don't implement it. It could be done in a general way to plug in responsive array props to components but that's a task for a separate PR (see [this](https://paulie.dev/posts/2020/08/styled-components-responsive-array-syntax/) as reference).
https://user-images.githubusercontent.com/81824236/113981324-33468f80-9850-11eb- …

Component - PancakeToggle

---

packages/pancake-uikit/package.json
packages/pancake-uikit/src/hooks/index.ts
packages/pancake-uikit/src/hooks/useTooltip/StyledTooltip.tsx
packages/pancake-uikit/src/hooks/useTooltip/index.tsx
packages/pancake-uikit/src/hooks/useTooltip/types.ts
packages/pancake-uikit/src/hooks/useTooltip/useTooltip.stories.tsx
packages/pancake-uikit/src/hooks/useTooltip/useTooltip.tsx
yarn.lock

This PR adds `useTooltip` hook.
Uses `Popper.js` and `react-popper` to position tooltip.
Minimal example (on hover)
```typescript
const { targetRef, tooltip, tooltipVisible } = useTooltip("Tooltip text", "top");
return (
<>
<button ref={targetRef}>hover me</button>
{tooltipVisible && tooltip}
</>
);
```

Feature: Add useTooltip hook

---

packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/widgets/Menu/components/Panel.tsx

Reverts https://github.com/pancakeswap/pancake-toolkit/pull/45 (GH was complaining when I tried to auto revert)
The language switcher's z-index is messed up

fix: Z index breaking language switcher

---

packages/pancake-uikit/src/__tests__/components/tabmenu.test.tsx
packages/pancake-uikit/src/components/Alert/theme.ts
packages/pancake-uikit/src/components/Card/theme.ts
packages/pancake-uikit/src/components/PancakeToggle/theme.ts
packages/pancake-uikit/src/components/Radio/theme.ts
packages/pancake-uikit/src/components/TabMenu/StyledTab.tsx
packages/pancake-uikit/src/components/TabMenu/Tab.tsx
packages/pancake-uikit/src/components/Toggle/theme.ts
packages/pancake-uikit/src/components/Tooltip/theme.ts
packages/pancake-uikit/src/theme/colors.ts
packages/pancake-uikit/src/theme/types.ts
packages/pancake-uikit/src/widgets/Menu/theme.ts
packages/pancake-uikit/src/widgets/Modal/theme.ts

A `card` color was set in the base theme, and was overrided by the theme object of the the Card component.
Rename this color from `card` to `backgroundAlt` fix the problem.

fix: Theme config key name

---

packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
packages/pancake-uikit/src/widgets/Modal/index.stories.tsx
packages/pancake-uikit/src/widgets/Modal/styles.tsx

Current application of the `background` style to `<ModalHeader/>` mean it blasts over its parent `<ModalContainer/>`'s border radius, resulting in:
- Added `overflow: hidden;` to modal container
- Fixed up some proptypes in the Modal story

feat(modal-bg): Add overflow hidden prop to Modal container and update storybook

---

packages/pancake-uikit/src/components/Card/CardRibbon.tsx
packages/pancake-uikit/src/components/Card/types.ts

- Using this component in the new pool cards
- Lack of z-index means with other card header elements it disappears behind them
- Added `...props` spreading to improve utility of component
Sad
Happy

fix(card-ribbon): Add z-index value to ribbon and spread props to improve flexibility of component

---

packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
packages/pancake-uikit/src/components/Svg/Icons/BunnyCards.tsx
packages/pancake-uikit/src/components/Svg/Icons/PocketWatch.tsx
packages/pancake-uikit/src/components/Svg/Icons/TeamPlayer.tsx
packages/pancake-uikit/src/components/Svg/Icons/Won.tsx
packages/pancake-uikit/src/widgets/WalletModal/icons/TrustWallet.tsx

Found an issue where if you were using more than 1 SVG that used `clipPath` than only 1 SVG would be displayed.

[UI Kit] fix(uikit): Unique ids for svgs that use clip path

---

packages/pancake-uikit/src/components/Slider/styles.ts

fix: Visible Border and background in ios for bunny slider thumb

---

packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/widgets/Menu/components/Logo.tsx

Viewport width is 160px and height is 26px, in order to get best results during transform animations we should stick with that ratios.

fix: Chrome blurs logo during scaling animation

---

packages/pancake-uikit/src/components/Heading/Heading.tsx
packages/pancake-uikit/src/components/Heading/index.stories.tsx
packages/pancake-uikit/src/components/Heading/index.tsx
packages/pancake-uikit/src/components/Heading/types.ts
packages/pancake-uikit/src/components/Text/Text.tsx
packages/pancake-uikit/src/components/Text/index.stories.tsx
packages/pancake-uikit/src/components/Text/types.ts

Recently, I have needed to restyle the `<Text>` component to have the display property: inline, for example when piecing together a single piece of text with different styles:
Or, a `<Balance>` component, preceded by a `~`
Both of these examples require a styled component to be initialised, with the required `display` style.
As per CR feedback - I am passing the styled system `{ layout }` styles to our Text component, allowing us to pass this display style as a prop, rather than needing to declare a styled component.
**Breaking changes**
- As `size` is a reserved styled-system `layout` prop, I've renamed this for headings to 'scale' - this matches the sizing props pattern used throughout the codebase (Button, Checkbox, Input, Toggle, Progress, Radio, Tag, Toggle)
- If we are happy with …

feat(text): Add styled system { layout } style to Text

---

packages/pancake-uikit/src/components/Button/theme.ts
packages/pancake-uikit/src/components/ButtonMenu/index.stories.tsx

- `tertiary` variant buttons should have white text in light mode, but `#27262c` in dark mode
Yes this is two commits for a one line change.

style(button): Add correct color for variants.SUBTLE button theme

---

packages/pancake-uikit/src/components/Slider/Slider.tsx

fix: Bunny slider progress width is too small when is leftmost and too big when is rightmost side

---

packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx
packages/pancake-uikit/src/widgets/Menu/components/MenuEntry.tsx
packages/pancake-uikit/src/widgets/Menu/components/MenuLink.tsx

The main menu had an issue with the button role, causing screen readers and tools like Vimium to interpret the functionless ``<div>``  wrapper around the menu links as button.
Before (what tools like Vimium see):
After:

fix(menu): Improved accessibility

---

netlify.toml

This PR adds netlify.toml config file
Since base dir is `packages/token-lists/` all changes in other directories will be ignored
Redirect is in place to redirect from `https://tokens.pancakeswap.finance` to `https://tokens.pancakeswap.finance/pancakeswap-default.json`
Tested on dummy netlify account

feat: Add netlify.toml for token-list redirect

---

packages/pancake-uikit/src/__tests__/components/dropdown.test.tsx
packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/components/Dropdown/Dropdown.tsx
packages/pancake-uikit/src/widgets/Menu/components/Panel.tsx

It is also so hard to change language in safari when clicking the language button mostly activates navigation bar, and in android it is not visible at first glance unless you scroll it
Before: 
https://user-images.githubusercontent.com/2213635/120793941-d3125800-c537-11eb-896b-93201fb34c23.mp4
After:
https://user-images.githubusercontent.com/2213635/120793989-e1607400-c537-11eb-888c-c20ec20c21c3.mp4
==================
It also fixes language selection menu top part is not visible in small screens (it is under the header bar) when in wallet browsers or safari with navigation bar at the bottom.
Before: 
https://user-images.githubusercontent.com/2213635/120794898-191beb80-c539-11eb-9661-04fab75d3bba.mp4
After:
https://user-images.githubusercontent.com/2213635/120795001-3486f680-c539-11eb-9044- …

fix: (Menu) Footer is not visible completely when navigation bar is visible in mobile browsers

---

.github/CODEOWNERS

Following #174 pull request updating CODEOWNERS for a specific package, we saw that it removed previous CODEOWNERS from the auto-review, as experienced in #181; this PR aims to add back previous owners.

chore: Update CODEOWNERS config

---

packages/pancake-uikit/src/widgets/Modal/ModalContext.tsx
packages/pancake-uikit/src/widgets/Modal/index.stories.tsx
packages/pancake-uikit/src/widgets/Modal/useModal.ts

Backstory:
Currently components that are passed to the `useModal()` hook are rendered once and never update unless you close the modal and reopen it again. This causes a wide range of troubles since all modals are basically isolated from the rest of the app due to inability to update via prop changes.
This PR provides backwards-compatible way to make components passed to `useModal()` hook react to changes. By default all `useModal()` hooks behave as they always were, now you can pass 3d argument `updateOnPropsChange` if you want modal component to be reactive to prop changes. Also 4th argument `modalId`(just string id) is required if you have multiple `useModal()` hook on the page to prevent one modal updating instead of the other. 
As noted in code comments - this solution feels a bit …

feature: Reactive modals

---

packages/pancake-uikit/src/components/Stepper/Step.tsx

Go to ifo
Go to how to take part section
See connector bar between steps sometimes not long enough.

fix: Increase ifo stepper connector height

---

packages/pancake-uikit/src/components/Message/Message.tsx

- Removed unused & conflicting svg alignSelf styles
- Wrap icon in Box to make it a block element, defaulting to displaying at the start of the flexed MessageContainer
Design specs for the `Message` component all look like:
But our previous Message styles apply this:

styles(message): Message component styling RE icon positioning

---

packages/pancake-uikit/src/__tests__/components/card.test.tsx
packages/pancake-uikit/src/components/Card/Card.tsx
packages/pancake-uikit/src/components/Card/CardHeader.tsx
packages/pancake-uikit/src/components/Card/CardRibbon.tsx
packages/pancake-uikit/src/components/Card/StyledCard.tsx
packages/pancake-uikit/src/components/Card/index.stories.tsx
packages/pancake-uikit/src/components/Card/types.ts

Borders are now the ones we use everywhere
`isActive` is the animated one we have in couple of places

feat: Update Card component

---

packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
packages/pancake-uikit/src/widgets/Menu/components/CakePrice.tsx

To reproduce:
1. Click cake price on the bottom of the menu
2. See the swap page output currency not set to cake

fix: Link of cake price to swap page is broken

---

packages/pancake-uikit/src/components/BottomNav/styles.tsx

When I was scrolling the new home page of pancakeswap on my cellphone, I just noticed that the bottom navbar was not handled well on iPhone:
This pull request should fix the problem with [`env()`](https://developer.mozilla.org/en-US/docs/Web/CSS/env()).

fix(uikit): BottomNav

---

packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx

Increase timeout inside DropdownMenu for all touch devices.
Prevent menu from closing before menuItem click event is catched.

fix(menu): Increase timeout on touch devices

---

packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx

I believe that `StyledOverlay ` should not be shown when [`showItemsOnMobile`](https://github.com/pancakeswap/pancake-frontend/blob/ecd69c44e997ad998bca75a6065d8280681d3c5b/src/components/Menu/config/config.ts#L11) is set to `false`.
Currently clicking the `Trade` menu would show an empty overlay which is superfluous in my opinion.
Here's how you can reproduce it:
1. open the home page on mobile phone
2. click the `Trade` menu on the bottom

fix(uikit): DropdownMenu

---

packages/pancake-uikit/src/widgets/Menu/Menu.tsx

Keep menu bar visible until user scrolled more than menu bar height, fixes below issue:

fix(Menu): Hide menu bar only when scrolled enough

---

packages/pancake-uikit/src/components/BottomNav/styles.tsx

Add fallbacks on some browsers that does not define `safe-area-inset-bottom`

fix: iOS bottom nav issue on specifics browsers

---

packages/pancake-uikit/src/components/MenuItem/styles.tsx

fix(uikit): Show active border on SubMenu when hover

---

packages/pancake-uikit/src/components/BottomNav/styles.tsx
packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx
packages/pancake-uikit/src/hooks/useOnClickOutside.ts

in some edge case, `mouseleave` won't trigger on touch mobile

fix(uikit): BottomNav clickoutside

---

packages/pancake-uikit/src/components/Slider/styles.ts

Currently visible like this in mobile safari

fix: (bunnyslider): Remove visible box shadow on slider thumb in mobile safari

---

packages/pancake-uikit/src/__tests__/components/overlay.test.tsx
packages/pancake-uikit/src/components/Overlay/Overlay.tsx

Remove backdrop filter that impact performance so much, not worth for that
before
https://user-images.githubusercontent.com/94336009/147495299-ff8f1b55-c1bf-4545-b116-1a3ef90e1530.mp4
after
https://user-images.githubusercontent.com/94336009/147495307-e360d12e-dfe3-400e-abae-52b9bad46aaf.mp4

perf(uikit): Remove backdrop filter

---

packages/pancake-uikit/src/components/Footer/config.tsx

The whale channel's, which has been deactivated since February 2021, link deleted,
3 official community channels links added.

feat(uikit): footer-telegram icon's tooltip update

---

packages/pancake-uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
packages/pancake-uikit/src/components/Overlay/Overlay.tsx

it's not recommend to use `overflow: overlay;`, still it's the only solution to workaround the layout shift on scrollbar.
we can remove this hack after this is working as expected https://github.com/pancakeswap/pancake-frontend/pull/2910

fix(uikit): Chrome scrollbar layoutshift

---

.eslintrc
packages/pancake-uikit/package.json
packages/pancake-uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
packages/pancake-uikit/src/components/BaseMenu/index.stories.tsx
packages/pancake-uikit/src/components/BottomNav/index.stories.tsx
packages/pancake-uikit/src/components/BottomNavItem/BottomNavItem.tsx
packages/pancake-uikit/src/components/BottomNavItem/index.stories.tsx
packages/pancake-uikit/src/components/Breadcrumbs/index.stories.tsx
packages/pancake-uikit/src/components/Button/IconButton.tsx
packages/pancake-uikit/src/components/Button/index.stories.tsx
packages/pancake-uikit/src/components/Button/types.ts
packages/pancake-uikit/src/components/ButtonMenu/ButtonMenuItem.tsx
packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx
packages/pancake-uikit/src/components/DropdownMenu/index.stories.tsx
packages/pancake-uikit/src/components/Footer/index.stories.tsx
packages/pancake-uikit/src/components/MenuItem/MenuItem.tsx
packages/pancake-uikit/src/components/MenuItem/index.stories.tsx
packages/pancake-uikit/src/components/MenuItems/index.stories.tsx
packages/pancake-uikit/src/components/SubMenuItems/index.stories.tsx
packages/pancake-uikit/src/util/polymorphic.ts
packages/pancake-uikit/src/widgets/Menu/Menu.tsx
packages/pancake-uikit/src/widgets/Menu/components/Logo.tsx
packages/pancake-uikit/src/widgets/Menu/config.ts
packages/pancake-uikit/src/widgets/Menu/context.ts
packages/pancake-uikit/src/widgets/Menu/index.stories.tsx
packages/pancake-uikit/src/widgets/Menu/types.ts

This contains Breaking Changes:
Menu component must provider `linkComponent` if using react router, default will be a normal `a` tag
```jsx
// react router
import { Link } from 'react-router-dom'
linkComponent: ({ href, ...props }) => {
return <Link to={href} {...props} />;
}
// nextjs
import Link from 'next/link'
linkComponent: ({ href, ...props }) => {
return <Link href={href} {...props} />;
},
```

refactor(uikit): Remove react router dom peerDependencies

---

packages/pancake-uikit/README.md

I have updated the readme file to point to the correct pancakeswap uikit npm package, it was using the older version which can be a bit confusing for people that wants to use the latest version. A note with the old name has been added too.

fix(uikit): Update the readme to point to the new package

---

packages/pancake-uikit/src/components/Image/tokens.ts
packages/token-lists/lists/pancakeswap-top-100.json
packages/token-lists/src/tokens/pancakeswap-top-100.json

Update the old btt token name to BTTOLD.
[x] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-uikit/blob/master/CONTRIBUTING.md) first
[x] If your PR is work in progress, open it as `draft`
[x] Before requesting a review, all the checks need to pass
[x] Explain what your PR does
After review, we found that the old BTT token was also included in the "pancakeswap-top-100.json" list, but the token name is not correct. so we raised a new PR to change the token name of old BTT as BTTOLD,  as a continuation of https://github.com/pancakeswap/pancake-toolkit/pull/401 
Otherwise, it may confuse the users, please help to review and merge it, thanks.

feat(token-list): update the btt token info

---

packages/pancake-uikit/src/components/Svg/Icons/Blocto.tsx
packages/pancake-uikit/src/widgets/WalletModal/config.tsx
packages/pancake-uikit/src/widgets/WalletModal/types.ts

Add [Blocto](https://blocto.portto.com) as a wallet option.
Blocto is a cross-platform, cross-chain wallet that can work either in normal browser, with web login experience similar to Fortmatic; and can also work in Blocto wallet app, with injected experience similar to Metamask or Trust wallet.
This PR is required for another PR in pancake-frontend https://github.com/pancakeswap/pancake-frontend/pull/2767

feat: Add Blocto to wallet options

---

package.json

`postinstall` on token list doesn't trigger on workspace
Related to #438

fix: Yarn postinstall workspace
