- package.json
https://github.com/pancakeswap/pancake-toolkit/pull/5
> fix: Format command

- packages/eslint-config-pancake/README.md
- packages/eslint-config-pancake/lib/index.js
- packages/eslint-config-pancake/package.json
- yarn.lock
Migrate https://github.com/pancakeswap/eslint-config-pancake
> feat: Add eslint package

- README.md
> doc: Add a readme at the workspace root

- package.json
- packages/eslint-config-pancake/package.json
- packages/pancake-uikit/package.json
> chore: Move husky hook to the root package.json

- lerna.json
> fix(lerna): Config

- packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/pancake-uikit/src/widgets/Modal/Modal.tsx
> feat: Add minWidth and headerBackground props to Modal

- packages/pancake-uikit/src/__tests__/components/button.test.tsx
- packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/pancake-uikit/src/components/Button/StyledButton.tsx
When button is in loading state, button should not be clickable but should not be affected by disabled styles and should be only affected by loading styles.
> fix: Button loading state

- packages/pancake-uikit/src/components/Button/ExpandableButton.tsx
- packages/pancake-uikit/src/components/Button/index.stories.tsx
- packages/pancake-uikit/src/components/Button/index.tsx
> feat: Add expandable buttons

- packages/pancake-uikit/package.json
- packages/pancake-uikit/src/__tests__/components/alert.test.tsx
- packages/pancake-uikit/src/__tests__/components/balanceinput.test.tsx
- packages/pancake-uikit/src/__tests__/components/breadcrumbs.test.tsx
- packages/pancake-uikit/src/__tests__/components/button.test.tsx
- packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
- packages/pancake-uikit/src/__tests__/components/card.test.tsx
- packages/pancake-uikit/src/__tests__/components/checkbox.test.tsx
- packages/pancake-uikit/src/__tests__/components/dropdown.test.tsx
- packages/pancake-uikit/src/__tests__/components/fallingbunnies.test.tsx
- packages/pancake-uikit/src/__tests__/components/flex.test.tsx
- packages/pancake-uikit/src/__tests__/components/heading.test.tsx
- packages/pancake-uikit/src/__tests__/components/input.test.tsx
- packages/pancake-uikit/src/__tests__/components/layouts.test.tsx
- packages/pancake-uikit/src/__tests__/components/link.test.tsx
- packages/pancake-uikit/src/__tests__/components/notificationdot.test.tsx
- packages/pancake-uikit/src/__tests__/components/overlay.test.tsx
- packages/pancake-uikit/src/__tests__/components/progress.test.tsx
- packages/pancake-uikit/src/__tests__/components/radio.test.tsx
- packages/pancake-uikit/src/__tests__/components/skeleton.test.tsx
- packages/pancake-uikit/src/__tests__/components/spinner.test.tsx
- packages/pancake-uikit/src/__tests__/components/svg.test.tsx
- packages/pancake-uikit/src/__tests__/components/tabmenu.test.tsx
- packages/pancake-uikit/src/__tests__/components/tag.test.tsx
- packages/pancake-uikit/src/__tests__/components/text.test.tsx
- packages/pancake-uikit/src/__tests__/components/toggle.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- yarn.lock
> [UI Kit] fix: Typing packages for peer deps

- .github/workflows/deploy-storybook.yml
> fix: Deployment script

- packages/pancake-uikit/src/components/Svg/Icons/Tune.tsx
- packages/pancake-uikit/src/components/Svg/index.tsx
Add [Tune icon](https://fonts.google.com/icons?selected=Material+Icons:tune)
> feat: Add Tune icon

- packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx
> fix: Accordion menu stuck at active state

- .github/CODEOWNERS
- packages/pancake-uikit/src/index.ts
> chore: Add Stepper export

- packages/pancake-uikit/src/components/Stepper/Step.tsx
> fix: Stepper connector visibility

- packages/pancake-uikit/src/components/Card/CardRibbon.tsx
- packages/pancake-uikit/src/components/Card/index.stories.tsx
- packages/pancake-uikit/src/components/Card/types.ts
> feat: Add left position for card ribbon

- packages/pancake-uikit/src/components/Stepper/Step.tsx
> fix: Stepper alignement

- packages/pancake-uikit/src/hooks/useTooltip/StyledTooltip.tsx
Add `z-index: 10` to the tooltip.
> fix: Add z-index 10 to StyledTooltip

- packages/pancake-uikit/src/__tests__/components/alert.test.tsx
- packages/pancake-uikit/src/__tests__/components/fallingbunnies.test.tsx
- packages/pancake-uikit/src/__tests__/components/link.test.tsx
- packages/pancake-uikit/src/__tests__/components/spinner.test.tsx
- packages/pancake-uikit/src/__tests__/components/svg.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/pancake-uikit/src/components/Stepper/Step.tsx
- packages/pancake-uikit/src/components/Svg/Svg.tsx
> Fix icon safari

- packages/pancake-uikit/src/components/Stepper/Step.tsx
> fix: Stepper layout

- packages/pancake-uikit/src/ResetCSS.tsx
- packages/pancake-uikit/src/__tests__/components/balanceinput.test.tsx
- packages/pancake-uikit/src/components/BalanceInput/BalanceInput.tsx
- packages/pancake-uikit/src/components/Stepper/Step.tsx
Update in the reset : https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp
> fix: Make BalanceInput a type="number"

- packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx
> fix: Accordion menu not showing new result when children changed

- packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
- packages/pancake-uikit/src/widgets/Menu/components/Accordion.tsx
- packages/pancake-uikit/src/widgets/Menu/components/PanelBody.tsx
- packages/pancake-uikit/src/widgets/Menu/config.ts
> feat(menu): Add support for top level tags on accordion

- packages/pancake-uikit/src/hooks/useTooltip/useTooltip.tsx
It affects to not able to click for example links inside tooltip element
Fixes https://github.com/pancakeswap/pancake-frontend/issues/1032
> fix: Tooltip on hover disappear immediately when mouse leaves target element

- packages/pancake-uikit/src/__tests__/widgets/menu.test.tsx
- packages/pancake-uikit/src/widgets/Menu/components/LangSelector.tsx
- packages/pancake-uikit/src/widgets/Menu/index.stories.tsx
- packages/pancake-uikit/src/widgets/Menu/index.ts
- packages/pancake-uikit/src/widgets/Menu/types.ts
- Rename LangType --> Language
> refactor(uikit): Add locale to match

- packages/eslint-config-pancake/package.json
- packages/pancake-uikit/package.json
> build: Change package domain

- packages/pancake-uikit/src/components/Card/theme.ts
- packages/pancake-uikit/src/components/Overlay/Overlay.tsx
- packages/pancake-uikit/src/components/Overlay/index.stories.tsx
- packages/pancake-uikit/src/theme/colors.ts
- packages/pancake-uikit/src/theme/types.ts
- packages/pancake-uikit/src/widgets/Menu/theme.ts
- packages/pancake-uikit/src/widgets/Menu/types.ts
> chore: Remove hardcoded colors in components

- packages/pancake-uikit/src/components/Card/index.stories.tsx
- packages/pancake-uikit/src/components/Card/theme.ts
- packages/pancake-uikit/src/components/Card/types.ts
> feat(uikit): Bubblegum card header variant

- packages/pancake-uikit/src/theme/colors.ts
- packages/pancake-uikit/src/theme/types.ts
Lil bitta bling
Adding the gradient for this kind of text element:
> chore(colors): Add gold gradient

- packages/pancake-uikit/src/__tests__/components/card.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/pancake-uikit/src/components/Card/CardFooter.tsx
- packages/pancake-uikit/src/theme/colors.ts
- packages/pancake-uikit/src/theme/types.ts
- packages/pancake-uikit/src/widgets/Modal/styles.tsx
Changes `borderColor` to `disabled` to match Figma.
> refactor(uikit): Theme color name update

- packages/pancake-uikit/src/__tests__/components/card.test.tsx
- packages/pancake-uikit/src/components/Card/StyledCard.tsx
- packages/pancake-uikit/src/theme/base.ts
Card radius change as per Bugs' request 🐛
> fix: Card radius

- packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
- packages/pancake-uikit/src/components/ButtonMenu/StyledButtonMenu.tsx
ButtonMenu outline as per Bugs' request 🐛
> fix: Add border to button menu

- packages/pancake-uikit/src/components/Message/Message.tsx
- packages/pancake-uikit/src/components/Message/index.stories.tsx
- packages/pancake-uikit/src/components/Message/index.ts
- packages/pancake-uikit/src/components/Message/theme.ts
- packages/pancake-uikit/src/components/Message/types.ts
- packages/pancake-uikit/src/index.ts
> feat: Message component

- packages/pancake-uikit/src/components/Message/Message.tsx
- packages/pancake-uikit/src/components/Text/Text.tsx
- packages/pancake-uikit/src/components/Text/index.stories.tsx
- packages/pancake-uikit/src/components/Text/types.ts
> feat: Add text ellipsis

- packages/pancake-uikit/src/__tests__/components/layouts.test.tsx
- packages/pancake-uikit/src/components/Box/Grid.tsx
- packages/pancake-uikit/src/components/Box/index.stories.tsx
- packages/pancake-uikit/src/components/Box/index.tsx
- packages/pancake-uikit/src/components/Box/types.ts
- packages/pancake-uikit/src/components/Layouts/BaseLayout.tsx
Add a grid primitive to build more complex layouts
> feat: Add a grid primitive

- packages/token-lists/lists/pancakeswap-extended.json
> fix: Tau coins

- packages/pancake-uikit/src/__tests__/components/breadcrumbs.test.tsx
- packages/pancake-uikit/src/components/Breadcrumbs/Breadcrumbs.tsx
> style(uikit): Breadcrump default color

- packages/token-lists/package.json
> build(token-lists): Set private to true to avoid publishing

- package.json
- yarn.lock
> chore: Bump babel version

- packages/pancake-uikit/src/components/Message/Message.tsx
- packages/pancake-uikit/src/components/Message/index.ts
> fix: Message component

- packages/pancake-uikit/src/widgets/Menu/components/UserBlock.tsx
Fixes https://github.com/pancakeswap/pancake-frontend/issues/1468
> fix: (userblock) Rerender userblock when one of the props changes

- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/pancake-uikit/src/widgets/WalletModal/ConnectModal.tsx
https://docs.pancakeswap.finance/get-started/connection-guide this link give more information than the previous one
> feat: (connect) Change how to connect link with more accurate one

- packages/pancake-uikit/src/hooks/useTooltip/index.tsx
- packages/pancake-uikit/src/widgets/Modal/Modal.tsx
- packages/pancake-uikit/src/widgets/Modal/index.stories.tsx
> chore: Custom modal header color from theme

- packages/token-lists/lists/pancakeswap-top-100.json
- packages/token-lists/package.json
- packages/token-lists/src/tokens/pancakeswap-top-100.json
> chore: Update token list

- packages/pancake-uikit/src/widgets/Menu/Menu.tsx
- packages/pancake-uikit/src/widgets/Menu/index.stories.tsx
- packages/pancake-uikit/src/widgets/Menu/types.ts
Info site doesn't need Connect button, this PR makes it optional.
> feat: Menu variant without Connect button

- packages/pancake-uikit/src/__tests__/widgets/modal.test.tsx
- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/pancake-uikit/src/widgets/Modal/index.stories.tsx
- packages/pancake-uikit/src/widgets/Modal/styles.tsx
> chore: Overflow scroll for modal body

- packages/pancake-uikit/src/__tests__/components/tokenimage.test.tsx
- packages/pancake-uikit/src/components/Image/Wrapper.tsx
- packages/pancake-uikit/src/components/Svg/Icons/Language.tsx
- packages/pancake-uikit/src/components/Svg/index.tsx
- packages/pancake-uikit/src/widgets/Menu/components/LangSelector.tsx
- packages/pancake-uikit/src/widgets/Menu/icons/index.ts
> Language icon

- packages/pancake-uikit/src/__tests__/components/tokenimage.test.tsx
- packages/pancake-uikit/src/components/Image/TokenImage.tsx
- packages/pancake-uikit/src/components/Image/TokenPairImage.tsx
- packages/pancake-uikit/src/components/Image/index.stories.tsx
- packages/pancake-uikit/src/components/Image/index.ts
- packages/pancake-uikit/src/components/Image/styles.tsx
- packages/pancake-uikit/src/components/Image/types.ts
> refactor(uikit/tokenimage): Accept full image src

- packages/pancake-uikit/src/widgets/Menu/components/CakePrice.tsx
> chore(uikit): Update cake price link

- .github/CODEOWNERS
> build(token-lists): Add code owner to folder

- packages/eslint-config-pancake/lib/index.js
Add [these rules from FE repo](https://github.com/pancakeswap/pancake-frontend/blob/develop/.eslintrc#L16-L19) into eslint-config-pancake package
> feat: Move ad-hoc FE rules to eslint-config

- packages/pancake-uikit/src/index.ts
> chore: Export overlay

- packages/pancake-uikit/src/components/Svg/Icons/SmallDot.tsx
- packages/pancake-uikit/src/components/Svg/index.tsx
> chore(svgs): Add small dot icon to uikit

- README.md
adding the pancake-profile-sdk and the token-lists package to the overview in the README.md file
> Update README.md for all available packages

- packages/token-lists/lists/pancakeswap-extended.json
- packages/token-lists/src/tokens/pancakeswap-extended.json
> chore: Remove Bondly

- packages/pancake-uikit/src/__tests__/widgets/walletModal.test.tsx
- packages/pancake-uikit/src/widgets/WalletModal/ConnectModal.tsx
- packages/pancake-uikit/src/widgets/WalletModal/WalletCard.tsx
- packages/pancake-uikit/src/widgets/WalletModal/config.tsx
Saves the last wallet in local storage and puts it as the first option.
> feat(uikit): Save last connected wallet

- packages/pancake-uikit/src/__tests__/components/buttonmenu.test.tsx
- packages/pancake-uikit/src/components/ButtonMenu/ButtonMenu.tsx
- packages/pancake-uikit/src/components/ButtonMenu/index.stories.tsx
- packages/pancake-uikit/src/components/ButtonMenu/types.ts
> feat(uikit-buttonmenu): Full width

- packages/pancake-uikit/src/components/Link/LinkExternal.tsx
- packages/pancake-uikit/src/components/SubMenu/SubMenu.tsx
- packages/pancake-uikit/src/components/SubMenu/index.stories.tsx
- packages/pancake-uikit/src/components/SubMenu/index.tsx
- packages/pancake-uikit/src/components/SubMenu/styles.tsx
- packages/pancake-uikit/src/index.ts
Uses popper js to position itself. The "button" is configurable via `component` prop
> feat: SubMenu component

- packages/pancake-uikit/src/theme/colors.ts
- packages/pancake-uikit/src/theme/types.ts
- packages/pancake-uikit/src/widgets/Menu/index.stories.tsx
> feat: Add medal colors

- packages/pancake-uikit/src/components/Table/Table.tsx
- packages/pancake-uikit/src/components/Table/index.stories.tsx
- packages/pancake-uikit/src/components/Table/index.tsx
> feat(uikit): Table

- packages/pancake-uikit/src/components/Image/BackgroundImage.tsx
- packages/pancake-uikit/src/components/Image/Image.tsx
- packages/pancake-uikit/src/components/Image/Placeholder.tsx
- packages/pancake-uikit/src/components/Image/ProfileAvatar.tsx
- packages/pancake-uikit/src/components/Image/index.stories.tsx
- packages/pancake-uikit/src/components/Image/index.ts
- packages/pancake-uikit/src/components/Image/types.ts
Adds placeholder to `BackgroundImage`
New `ProfileAvatar` component
> [UI Kit] Feature/profile avatar

- packages/pancake-uikit/src/components/Table/Cell.tsx
- packages/pancake-uikit/src/components/Table/Table.tsx
- packages/pancake-uikit/src/components/Table/index.stories.tsx
- packages/pancake-uikit/src/components/Table/index.tsx
Adds `<Td />` and `<Th />` with `typography` props
> feat(uikit): Td & Th components

- packages/pancake-uikit/src/theme/index.ts
> chore(uikit): Export theme types

- packages/pancake-uikit/src/components/Input/InputGroup.tsx
- packages/pancake-uikit/src/components/Input/index.stories.tsx
- packages/pancake-uikit/src/components/Input/index.tsx
- packages/pancake-uikit/src/components/Input/types.ts
> feat(uikit): Input Group

- packages/token-lists/lists/pancakeswap-top-100.json
- packages/token-lists/package.json
- packages/token-lists/src/tokens/pancakeswap-top-100.json
- packages/token-lists/src/top-100.ts
- Update tokens to exclude by default
- Add broken tokens
- Sanitize name/ticker of tokens
- Re-generate Top100 token list
> fix(token-lists): Top100 sanitization

- packages/pancake-uikit/src/components/BalanceInput/TextField.tsx
- packages/pancake-uikit/src/components/BalanceInput/index.stories.tsx
- packages/pancake-uikit/src/components/BalanceInput/index.tsx
- packages/pancake-uikit/src/components/BalanceInput/styles.tsx
- packages/pancake-uikit/src/components/BalanceInput/types.ts
> feat(uikit): TextField

- packages/pancake-uikit/src/components/Button/theme.ts
- packages/pancake-uikit/src/components/Button/types.ts
> feat(uikit): Button light variant

- packages/pancake-uikit/src/components/CakePrice/CakePrice.tsx
- packages/pancake-uikit/src/components/CakePrice/index.stories.tsx
- packages/pancake-uikit/src/components/CakePrice/index.tsx
- packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx
- packages/pancake-uikit/src/components/DropdownMenu/styles.tsx
- packages/pancake-uikit/src/components/Footer/Footer.tsx
- packages/pancake-uikit/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- packages/pancake-uikit/src/components/ThemeSwitcher/index.stories.tsx
- packages/pancake-uikit/src/components/ThemeSwitcher/index.tsx
- packages/pancake-uikit/src/index.ts
- export ThemeSwitcher
- add overlay for BottomNav
- add some missing stories
> feat(menu rework): Menu rework adjustments

- packages/pancake-uikit/src/components/Timeline/InfoTooltip.tsx
- packages/pancake-uikit/src/components/Timeline/Timeline.tsx
- packages/pancake-uikit/src/components/Timeline/index.stories.tsx
- packages/pancake-uikit/src/components/Timeline/index.ts
- packages/pancake-uikit/src/components/Timeline/styles.ts
- packages/pancake-uikit/src/components/Timeline/types.ts
- packages/pancake-uikit/src/index.ts
[Preview link](https://pancake-timeline.surge.sh/?path=/story/components-timeline--default)
> feat(timeline): Add timeline component

- packages/pancake-uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
- packages/pancake-uikit/src/components/Footer/Footer.tsx
Add rel attribute to open footer links in separate tabs.
> fix(footer links): Add rel attribute

- packages/pancake-uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
- packages/pancake-uikit/src/widgets/Menu/Menu.tsx
We need to push content inside BodyWrapper when there is no SubNav.
> fix(menu): Apply margin to BodyWrapper

- packages/token-lists/lists/pancakeswap-top-100.json
- packages/token-lists/src/tokens/pancakeswap-top-100.json
> fix: XWG Decimals

- packages/pancake-uikit/src/widgets/Menu/components/UserMenu/index.tsx
It happens not always but intermittently
https://user-images.githubusercontent.com/2213635/133599672-d4c109c5-a733-41dc-98bc-1d3793f91458.mp4
> fix: User menu item on click action not triggered intermittently

- packages/pancake-uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
- packages/pancake-uikit/src/components/SubMenuItems/styles.tsx
- packages/pancake-uikit/src/components/SubMenuItems/types.ts
> fix(menu): Submenu types

- packages/pancake-uikit/src/components/BottomNav/mock.tsx
- packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx
- packages/pancake-uikit/src/components/DropdownMenu/types.ts
fix regression #280
`StyledOverlay` showing when `showItemsOnMobile` is false
> fix(uikit): Mobile overlay regression

- packages/pancake-uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
- packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx
- packages/pancake-uikit/src/components/DropdownMenu/types.ts
- packages/pancake-uikit/src/components/MenuItem/MenuItem.tsx
- packages/pancake-uikit/src/components/MenuItem/types.ts
- packages/pancake-uikit/src/components/MenuItems/MenuItems.tsx
Fix few bugs for the menu on touch devices
1. menu position 
2. href is `"/"` when it has sub items
3. sub menu link is not working at all
https://user-images.githubusercontent.com/94336009/142806223-b50fea96-6c80-4389-9d0a-3c0c8518d074.mp4
> fix(uikit): Menu position incorrect and link no response on touch device

- packages/pancake-uikit/package.json
- packages/pancake-uikit/src/__tests__/widgets/__snapshots__/menu.test.tsx.snap
- packages/pancake-uikit/src/components/DropdownMenu/DropdownMenu.tsx
- packages/pancake-uikit/src/components/MenuItem/styles.tsx
- packages/pancake-uikit/src/widgets/Menu/Menu.tsx
- packages/pancake-uikit/src/widgets/Menu/components/UserMenu/index.tsx
- packages/pancake-uikit/src/widgets/Menu/index.stories.tsx
1. UserMenu position incorrect, due to Banner, use popper strategy `fixed`
2. Make dropdown menu can be closed by clicking the menu button
3. Fix Submenu border z index
> fix(uikit): UserMenu position incorrect

- packages/pancake-uikit/src/components/BottomDrawer/BottomDrawer.tsx
- packages/pancake-uikit/src/components/BottomDrawer/index.stories.tsx
- packages/pancake-uikit/src/components/BottomDrawer/index.ts
- packages/pancake-uikit/src/components/BottomDrawer/styles.ts
- packages/pancake-uikit/src/hooks/index.ts
- packages/pancake-uikit/src/hooks/useDelayedUnmount.ts
- packages/pancake-uikit/src/hooks/useOnClickOutside.ts
- packages/pancake-uikit/src/index.ts
- packages/pancake-uikit/src/widgets/Menu/index.stories.tsx
> feat: BottomDrawer

- packages/pancake-uikit/src/components/Message/Message.tsx
- packages/pancake-uikit/src/components/Message/index.stories.tsx
- packages/pancake-uikit/src/components/Message/index.ts
- packages/pancake-uikit/src/components/Message/theme.ts
- packages/pancake-uikit/src/components/Message/types.ts
> feat(uikit): Add MessageText for Message
